#ifndef __MAIN_H__
#define __MAIN_H__
#include "common.h"
#include "stm32f4xx.h"
#include "SuperviseTask.h"
#include "ad.h"
#include "gun.h"
#include "common.h"
#include "can1.h"
#include "can2.h"
#include "delay.h"
#include "timer.h"
#include "usart1.h"
#include "usart3.h"
#include "led.h"
#include "oled.h"
#include "bsp_flash.h"
#include <stdio.h>
#include <math.h>
#include <string.h>
#include <stdarg.h>
#include "mpu6050_interrupt.h"
#include "mpu6050_driver.h"
#include "mpu6050_i2c.h"
#include "imu.h"
#include "ramp.h"
#include "CanBusTask.h"
#include "pid.h"
#include "pid_regulator.h"      
#include "laser.h"
#include "bsp.h"
#include "encoder.h"
#include "ControlTask.h"
#include "LostCounter.h"
#include "SuperviseTask.h"
#include "RemoteTask.h"
#include "IOTask.h"
#include "protocal.h"

#endif 
